id: AC27756F6
base_file: f62BE.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 20:50:53.095475
  last_modified_at: 2022-05-30 20:50:53.095511
